-- 1.1

CREATE TABLE REGION
    (ID NUMBER(7), NAME VARCHAR2(25)
    );

ALTER TABLE REGION
    ADD PRIMARY KEY (ID);
ALTER TABLE REGION
    MODIFY NAME CONSTRAINT REG_NAME_NN NOT NULL;
ALTER TABLE REGION
    MODIFY NAME DEFAULT 'Новий регіон';

CREATE TABLE DEPARTMENT
    (ID                                            NUMBER(7),
     NAME                                          VARCHAR2(25)
         CONSTRAINT DEP_NAME_NN NOT NULL,
     REGION_ID                                     NUMBER(7),
     CONSTRAINT DEP_PK PRIMARY KEY (ID),
     CONSTRAINT DEP_REG_FK FOREIGN KEY (REGION_ID)
         REFERENCES REGION (ID),
     CONSTRAINT DEP_UK UNIQUE (REGION_ID)
    );

CREATE TABLE EMPLOYEE
    (ID                                                               NUMBER(7)
         CONSTRAINT EMP_PK PRIMARY KEY, LAST_NAME                     VARCHAR2(25)
         CONSTRAINT EMP_LAST_NAME_NN NOT NULL, FIRST_NAME             VARCHAR2(25), USER_ID CHAR(12)
         CONSTRAINT EMP_USER_ID_NN NOT NULL
         CONSTRAINT EMP_UK UNIQUE, DEPT_ID                            NUMBER(7)
         CONSTRAINT EMP_DEPT_ID_NN NOT NULL
         CONSTRAINT EMP_DEP_FK REFERENCES DEPARTMENT (ID), START_DATE DATE DEFAULT SYSDATE, COMISSION NUMBER(7)
         CONSTRAINT EMP_COMISSION_CK CHECK (COMISSION >= 10 AND COMISSION <= 50)
    );

-- 1.2

CREATE INDEX DEP_REGION_ID_I ON DEPARTMENT (REGION_ID);
CREATE INDEX EMP_DEPT_ID_I ON EMPLOYEE (DEPT_ID);

CREATE INDEX REG_NAME_I ON REGION (NAME);
CREATE INDEX DEP_NAME_I ON DEPARTMENT (NAME);
CREATE INDEX EMP_LAST_NAME_I ON EMPLOYEE (LAST_NAME);

-- 1.3

SELECT *
FROM USER_TABLES;

SELECT *
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'REGION';

SELECT *
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'DEPARTMENT';

SELECT *
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EMPLOYEE';

SELECT *
FROM USER_CONSTRAINTS;
SELECT *
FROM USER_INDEXES;


-- 2.1

CREATE TABLE WORKER AS
SELECT *
FROM EMPLOYEE;

SELECT *
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'WORKER';

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'WORKER';


-- 2.2

ALTER TABLE WORKER
    ADD CONSTRAINT WORK_PK PRIMARY KEY (ID) ENABLE;

-- 2.3

ALTER TABLE WORKER
    ADD CONSTRAINT WORK_DEP_FK FOREIGN
        KEY (DEPT_ID) REFERENCES DEPARTMENT (ID);

-- 2.4

ALTER TABLE DEPARTMENT
    ADD DEPT_ID NUMBER(7)
        CONSTRAINT
            DEP_DEP_FK REFERENCES DEPARTMENT (ID);

-- 2.5

ALTER TABLE WORKER
    ADD TITLE VARCHAR2(30);


-- 2.6

DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;


-- 2.7

CREATE SEQUENCE DEP_PK_SEQ
    START WITH 76 MAXVALUE 80 INCREMENT BY 1;


-- 2.8

SELECT DEP_PK_SEQ.NEXTVAL
FROM DUAL;

SELECT DEP_PK_SEQ.CURRVAL
FROM DUAL;

SELECT *
FROM USER_SEQUENCES; 
